apiVersion: v1
kind: Secret
metadata:
  name: node-manager-secret
  namespace: rogers-5g-production
type: Opaque
data:
  auth_token: ZGdsYS1ub2RlLW1hbmFnZXItdG9rZW4= # dgla-node-manager-token (change in production)
