apiVersion: v1
kind: Service
metadata:
  name: rogers-5g-production-sla-service
  namespace: rogers-5g-production
spec:
  selector:
    app: dgla-sla-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
