apiVersion: v1
kind: Service
metadata:
  name: rogers-5g-production-cdn-service
  namespace: rogers-5g-production
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: dgla-cdn
