apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rogers-5g-production-mongodb
  namespace: rogers-5g-production
spec:
  serviceName: mongodb
  replicas: 3
  selector:
    matchLabels:
      app: dgla-mongodb
  template:
    metadata:
      labels:
        app: dgla-mongodb
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: mongodb
        image: dgla/mongodb-merkle:latest
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        - name: MONGO_MERKLE_SECRET
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: merkle_key
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi
