apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: rogers-5g-production
type: Opaque
data:
  username: YWRtaW4= # admin
  password: cGFzc3dvcmQ= # password (change in production)
  merkle_key: bWVya2xlLWtleS1zZWNyZXQ= # merkle-key-secret (change in production)
