apiVersion: v1
kind: Service
metadata:
  name: rogers-5g-production-mongodb
  namespace: rogers-5g-production
  labels:
    app: dgla-mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  clusterIP: None
  selector:
    app: dgla-mongodb
